# Generated by Django 2.2.7 on 2019-11-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_type',
            new_name='blogtypename',
        ),
    ]
