# Generated by Django 2.2.7 on 2019-12-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191203_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadBlog',
            new_name='ReadNum',
        ),
    ]
