# Generated by Django 2.2.7 on 2019-12-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191203_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
